/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["month"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addAlias"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["explain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set"];
        post?: never;
        delete: operations["clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** @example RON */
            currency: string;
            /** @description e.g. RO49 •••• 0000; absent when the IBAN is unknown */
            ibanMasked?: string;
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            kind: "CURRENT" | "SAVINGS" | "CARD";
            name: string;
        };
        AccountImport: {
            account: components["schemas"]["Account"];
            /** Format: int32 */
            alreadyImported: number;
            /** @description Detected for the first time by this upload */
            created: boolean;
            /** Format: int32 */
            newTransactions: number;
            /** Format: date */
            periodFrom?: string;
            /** Format: date */
            periodTo?: string;
        };
        AliasResult: {
            /** Format: int32 */
            movedTransactions: number;
            /** Format: int32 */
            recategorizedTransactions: number;
        };
        Category: {
            /** @example GROCERIES */
            code: string;
            /** Format: int64 */
            id: number;
            /**
             * @description Only SPEND counts towards spent
             * @enum {string}
             */
            kind: "SPEND" | "INCOME" | "TRANSFER";
            /** @example Groceries */
            name: string;
            /** Format: int64 */
            parentId?: number;
        };
        CategoryChange: {
            /**
             * Format: int32
             * @description Transactions whose category changed, this one included
             */
            changedTransactions: number;
            transaction: components["schemas"]["TransactionView"];
        };
        CategorySpend: {
            /** Format: int64 */
            categoryId?: number;
            code?: string;
            /**
             * Format: int32
             * @description vs. usual; absent when there is no usual to compare with
             */
            deltaPct?: number;
            name: string;
            /**
             * Format: int32
             * @description Of the month's spent
             */
            sharePct: number;
            /** Format: int64 */
            spentMinor: number;
            /** Format: int32 */
            transactionCount: number;
            /**
             * Format: int64
             * @description Average over the baseline months
             */
            usualMinor: number;
        };
        Explanation: {
            categoryCode?: string;
            /** @description Which tier would categorize it: RULE, LEARNED or KEYWORD; absent when none */
            categorySource?: string;
            key: string;
            steps: components["schemas"]["Step"][];
        };
        FileOutcome: {
            /** Format: int64 */
            accountId?: number;
            /**
             * Format: int32
             * @description Rows already imported by an earlier file
             */
            alreadyImported: number;
            /** @description Parser scores, best first; filled when the user has to pick (NEEDS_PARSER) */
            candidates: components["schemas"]["ParserCandidate"][];
            fileName: string;
            /** @description Why the file was not imported, in words for the user */
            message?: string;
            /** Format: int32 */
            newTransactions: number;
            parserId?: string;
            /** Format: date */
            periodFrom?: string;
            /** Format: date */
            periodTo?: string;
            /** Format: int32 */
            rows: number;
            /** @enum {string} */
            status: "IMPORTED" | "DUPLICATE_FILE" | "NEEDS_PARSER" | "NEEDS_ACCOUNT" | "FAILED";
        };
        HealthResponse: {
            /** @enum {string} */
            database: "UP" | "DOWN";
            /** @description Applied Flyway version; absent when the database is down */
            schemaVersion?: string;
            /** @enum {string} */
            status: "UP" | "DOWN";
        };
        ImportSummary: {
            accounts: components["schemas"]["AccountImport"][];
            /** Format: int32 */
            alreadyImported: number;
            files: components["schemas"]["FileOutcome"][];
            /** Format: int32 */
            newTransactions: number;
        };
        MerchantSummary: {
            categoryCode?: string;
            displayName: string;
            /** Format: int64 */
            id: number;
            key: string;
            /** @description Up to 3 distinct raw descriptions, IBANs masked */
            sampleDescriptions: string[];
            /** Format: int64 */
            transactionCount: number;
        };
        MonthSummary: {
            /**
             * Format: int32
             * @description Share of this month's spending to trust: weighted by category confidence
             */
            accuracyPct: number;
            /** @description Months with data, oldest first, e.g. 2026-01 */
            availableMonths: string[];
            /**
             * Format: int64
             * @description Average spent over the baseline months; absent without history
             */
            averageSpentMinor?: number;
            /**
             * Format: int32
             * @description How many of the previous 3 months have data; the average uses only those
             */
            baselineMonths: number;
            /** @description Top 5 by spent, largest first */
            categories: components["schemas"]["CategorySpend"][];
            /**
             * Format: int32
             * @description Share of this month's spending with any category
             */
            categorizedPct: number;
            /** @example RON */
            currency: string;
            /**
             * Format: int32
             * @description Spent vs. that average, e.g. 12 for +12%; absent without history or when it is 0
             */
            deltaPct?: number;
            /** Format: int64 */
            incomeMinor: number;
            /** @example 2026-03 */
            month: string;
            /**
             * Format: int64
             * @description Income − spent; negative when spending more
             */
            netMinor: number;
            /** @description Everything below the top 5, folded */
            rest: components["schemas"]["Rest"];
            /** Format: int64 */
            spentMinor: number;
            /** Format: int32 */
            uncategorizedCount: number;
            /**
             * Format: int64
             * @description Spent without a category, wherever it ranks (it may be folded into the rest)
             */
            uncategorizedMinor: number;
        };
        NewAccount: {
            /** @example RON */
            currency: string;
            /** @enum {string} */
            kind: "CURRENT" | "SAVINGS" | "CARD";
            name: string;
        };
        NewAlias: {
            /** @enum {string} */
            matchType: "EXACT" | "PREFIX";
            merchantKey: string;
            /** @description Matched against the merchant key */
            pattern: string;
        };
        ParserCandidate: {
            name: string;
            parserId: string;
            reason: string;
            /**
             * Format: double
             * @description 0..1
             */
            score: number;
        };
        Rest: {
            /** Format: int32 */
            categoryCount: number;
            /** Format: int32 */
            sharePct: number;
            /** Format: int64 */
            spentMinor: number;
        };
        SetCategory: {
            /** @description Answer to 'apply to this merchant from now on?': creates a rule for the merchant */
            applyToMerchant?: boolean;
            /** Format: int64 */
            categoryId: number;
        };
        Step: {
            name?: string;
            output?: string;
        };
        TransactionView: {
            /** Format: int64 */
            accountId: number;
            /**
             * Format: int64
             * @description Signed minor units; negative = money out
             */
            amountMinor: number;
            /** Format: date */
            bookingDate: string;
            categoryCode?: string;
            categoryConfidence?: number;
            /** Format: int64 */
            categoryId?: number;
            /** @description USER, RULE, LEARNED, MCC, KEYWORD, SYSTEM; absent when uncategorized */
            categorySource?: string;
            /** @example RON */
            currency: string;
            /** @description Bank text with IBANs masked */
            description: string;
            /** Format: int64 */
            id: number;
            merchantKey: string;
            merchantName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccount"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    importFiles: {
        parameters: {
            query?: {
                /** @description Account for files that do not name one (no IBAN) */
                accountId?: number;
                /** @description Force a parser instead of detection, e.g. after NEEDS_PARSER */
                parserId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
        };
    };
    month: {
        parameters: {
            query?: {
                /** @description YYYY-MM; defaults to the latest month with data */
                month?: string;
                /** @description ISO currency; v1 reports one currency at a time */
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSummary"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantSummary"][];
                };
            };
        };
    };
    addAlias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAlias"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasResult"];
                };
            };
        };
    };
    explain: {
        parameters: {
            query: {
                raw: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
        };
    };
    set: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCategory"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryChange"];
                };
            };
        };
    };
    clear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryChange"];
                };
            };
        };
    };
}
