-- M1 / CP1.1: import and identity schema (DESIGN: Data model, Transaction identity and idempotency).
-- Facts (raw_row, transaction) are immutable or append-only. Interpretations (merchant, category, transfer pair,
-- subscription) get their own columns/tables in later migrations, alongside the tables they reference.

CREATE TABLE household (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE app_user (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id bigint NOT NULL REFERENCES household (id),
    email        text UNIQUE
);

-- v1 is single-user and local: one seeded household and user (no auth). Ownership never needs a migration later.
INSERT INTO household (id, name) VALUES (1, 'Home');
INSERT INTO app_user (id, household_id, email) VALUES (1, 1, NULL);
SELECT setval(pg_get_serial_sequence('household', 'id'), 1);
SELECT setval(pg_get_serial_sequence('app_user', 'id'), 1);

CREATE TABLE account (
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    household_id  bigint NOT NULL REFERENCES household (id),
    owner_user_id bigint NOT NULL REFERENCES app_user (id),
    name          text   NOT NULL,
    -- IBANs are never stored in plain form: HMAC-SHA256 for matching, masked form for display.
    iban_hash     bytea CHECK (octet_length(iban_hash) = 32),
    iban_masked   text CHECK (length(regexp_replace(iban_masked, '[^0-9]', '', 'g')) <= 6),
    currency      char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    kind          text    NOT NULL CHECK (kind IN ('CURRENT', 'SAVINGS', 'CARD')),
    visibility    text    NOT NULL DEFAULT 'PRIVATE' CHECK (visibility IN ('PRIVATE', 'HOUSEHOLD')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    CHECK ((iban_hash IS NULL) = (iban_masked IS NULL))
);

CREATE UNIQUE INDEX account_household_iban_uq ON account (household_id, iban_hash) WHERE iban_hash IS NOT NULL;

CREATE TABLE statement_file (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id  bigint NOT NULL REFERENCES account (id),
    sha256      bytea  NOT NULL CHECK (octet_length(sha256) = 32),
    format      text   NOT NULL, -- parser id, e.g. 'generic-csv-v1'
    file_name   text,
    period_from date,
    period_to   date,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    status      text NOT NULL CHECK (status IN ('IMPORTED', 'FAILED')),
    -- exact re-upload of the same file for the same account is a no-op
    CONSTRAINT statement_file_account_sha256_uq UNIQUE (account_id, sha256),
    CHECK (period_from IS NULL OR period_to IS NULL OR period_from <= period_to)
);

CREATE TABLE raw_row (
    id                bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    statement_file_id bigint  NOT NULL REFERENCES statement_file (id),
    row_no            integer NOT NULL CHECK (row_no >= 1),
    payload           jsonb   NOT NULL,
    CONSTRAINT raw_row_file_row_uq UNIQUE (statement_file_id, row_no)
);

-- Raw rows are the source for every re-run; the database refuses to change or remove them.
CREATE FUNCTION raw_row_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'raw_row is immutable (% on id %)', TG_OP, OLD.id;
END;
$$;

CREATE TRIGGER raw_row_immutable
    BEFORE UPDATE OR DELETE ON raw_row
    FOR EACH ROW EXECUTE FUNCTION raw_row_immutable();

CREATE TABLE transaction (
    id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    household_id     bigint NOT NULL REFERENCES household (id),
    account_id       bigint NOT NULL REFERENCES account (id),
    -- 'ref:<bank reference>' or '<key version>:<content hash>#<occurrence>'; see CP1.3
    identity_key     text   NOT NULL,
    booking_date     date   NOT NULL,
    value_date       date,
    amount_minor     bigint NOT NULL, -- signed minor units: negative = money out
    currency         char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    description_raw  text   NOT NULL,
    description_norm text   NOT NULL,
    status           text   NOT NULL CHECK (status IN ('PENDING', 'POSTED')),
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT transaction_account_identity_uq UNIQUE (account_id, identity_key)
);

CREATE INDEX transaction_household_booking_idx ON transaction (household_id, booking_date);

-- Many raw rows → one transaction when the same record arrives in several files; a raw row maps to one transaction.
CREATE TABLE transaction_source (
    transaction_id bigint NOT NULL REFERENCES transaction (id),
    raw_row_id     bigint NOT NULL REFERENCES raw_row (id),
    PRIMARY KEY (transaction_id, raw_row_id),
    CONSTRAINT transaction_source_raw_row_uq UNIQUE (raw_row_id)
);
