-- M2 / CP2.2: categories and resolution (DESIGN: Category resolution, Seed categories).
-- A transaction's category is an interpretation with its source; only automation-set categories are ever recomputed.

CREATE TABLE category (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  bigint REFERENCES category (id),
    code       text NOT NULL CHECK (code ~ '^[A-Z][A-Z_]*$'),
    name       text NOT NULL,
    -- SPEND counts towards "spent"; INCOME and TRANSFER never do (DESIGN: Home screen design rules).
    kind       text NOT NULL CHECK (kind IN ('SPEND', 'INCOME', 'TRANSFER')),
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT category_code_uq UNIQUE (code)
);

INSERT INTO category (id, code, name, kind, sort_order) VALUES
    (1, 'GROCERIES', 'Groceries', 'SPEND', 10),
    (2, 'RESTAURANTS', 'Restaurants & cafés', 'SPEND', 20),
    (3, 'TRANSPORT', 'Transport', 'SPEND', 30),
    (4, 'FUEL', 'Fuel', 'SPEND', 40),
    (5, 'UTILITIES', 'Utilities', 'SPEND', 50),
    (6, 'TELECOM', 'Telecom & internet', 'SPEND', 60),
    (7, 'HOUSING', 'Housing', 'SPEND', 70),
    (8, 'HEALTH', 'Health & pharmacy', 'SPEND', 80),
    (9, 'ENTERTAINMENT', 'Entertainment', 'SPEND', 90),
    (10, 'SUBSCRIPTIONS', 'Subscriptions & software', 'SPEND', 100),
    (11, 'SHOPPING', 'Shopping', 'SPEND', 110),
    (12, 'TRAVEL', 'Travel', 'SPEND', 120),
    (13, 'EDUCATION', 'Education', 'SPEND', 130),
    (14, 'FEES', 'Fees & interest', 'SPEND', 140),
    (15, 'INCOME', 'Income', 'INCOME', 150),
    (16, 'TRANSFER', 'Transfer', 'TRANSFER', 160),
    (17, 'CASH', 'Cash withdrawal', 'SPEND', 170),
    (18, 'OTHER', 'Other', 'SPEND', 180);
SELECT setval(pg_get_serial_sequence('category', 'id'), 1000); -- user-added categories start at 1001

-- Tier 1 (USER, from "apply to this merchant") and tier 4 (SEED keywords). Patterns match the merchant key:
-- MERCHANT = the whole key, KEYWORD = consecutive whole words anywhere in it.
CREATE TABLE category_rule (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    household_id bigint NOT NULL REFERENCES household (id),
    source       text   NOT NULL CHECK (source IN ('USER', 'SEED')),
    priority     integer NOT NULL DEFAULT 100,
    match_type   text   NOT NULL CHECK (match_type IN ('MERCHANT', 'KEYWORD')),
    pattern      text   NOT NULL CHECK (pattern <> '' AND pattern = upper(pattern)),
    category_id  bigint NOT NULL REFERENCES category (id),
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT category_rule_uq UNIQUE (household_id, source, match_type, pattern)
);

-- Tier 2: learned from the user's confirmations (written by CP2.3's recategorize endpoint).
ALTER TABLE merchant ADD COLUMN default_category_id bigint REFERENCES category (id);

ALTER TABLE transaction
    ADD COLUMN category_id bigint REFERENCES category (id),
    -- USER = set by hand on this transaction: automation never touches it again.
    ADD COLUMN category_source text CHECK (category_source IN ('USER', 'RULE', 'LEARNED', 'MCC', 'KEYWORD', 'SYSTEM')),
    ADD COLUMN category_confidence numeric(3, 2) CHECK (category_confidence BETWEEN 0 AND 1),
    ADD CONSTRAINT transaction_category_source_ck CHECK ((category_id IS NULL) = (category_source IS NULL));

CREATE INDEX transaction_category_idx ON transaction (category_id);

INSERT INTO category_rule (household_id, source, match_type, pattern, category_id)
SELECT 1, 'SEED', 'KEYWORD', k.pattern, c.id
FROM (VALUES
    ('GROCERIES', 'KAUFLAND'), ('GROCERIES', 'LIDL'), ('GROCERIES', 'MEGA IMAGE'), ('GROCERIES', 'CARREFOUR'),
    ('GROCERIES', 'AUCHAN'), ('GROCERIES', 'PROFI'), ('GROCERIES', 'PENNY'), ('GROCERIES', 'LA DOI PASI'),
    ('GROCERIES', 'SELGROS'), ('GROCERIES', 'METRO'), ('GROCERIES', 'CORA'), ('GROCERIES', 'FRESHFUL'),
    ('GROCERIES', 'BRINGO'), ('GROCERIES', 'SUPERMARKET'), ('GROCERIES', 'MARKET'),
    ('RESTAURANTS', 'STARBUCKS'), ('RESTAURANTS', 'MCDONALDS'), ('RESTAURANTS', 'KFC'), ('RESTAURANTS', 'GLOVO'),
    ('RESTAURANTS', 'TAZZ'), ('RESTAURANTS', 'FOODPANDA'), ('RESTAURANTS', 'BURGER KING'), ('RESTAURANTS', 'SUBWAY'),
    ('RESTAURANTS', 'RESTAURANT'), ('RESTAURANTS', 'CAFE'), ('RESTAURANTS', 'COFFEE'), ('RESTAURANTS', 'PIZZA'),
    ('RESTAURANTS', 'BISTRO'), ('RESTAURANTS', 'TRATTORIA'),
    ('TRANSPORT', 'BOLT'), ('TRANSPORT', 'UBER'), ('TRANSPORT', 'FREE NOW'), ('TRANSPORT', 'STB'),
    ('TRANSPORT', 'METROREX'), ('TRANSPORT', 'CFR'), ('TRANSPORT', 'TAXI'), ('TRANSPORT', 'PARCARE'),
    ('TRANSPORT', 'PARKING'),
    ('FUEL', 'OMV'), ('FUEL', 'PETROM'), ('FUEL', 'MOL'), ('FUEL', 'ROMPETROL'), ('FUEL', 'LUKOIL'),
    ('FUEL', 'SOCAR'), ('FUEL', 'GAZPROM'),
    ('UTILITIES', 'ENEL'), ('UTILITIES', 'ENGIE'), ('UTILITIES', 'EON'), ('UTILITIES', 'APA NOVA'),
    ('UTILITIES', 'ELECTRICA'), ('UTILITIES', 'HIDROELECTRICA'), ('UTILITIES', 'PPC'), ('UTILITIES', 'TERMOENERGETICA'),
    ('TELECOM', 'ORANGE'), ('TELECOM', 'VODAFONE'), ('TELECOM', 'TELEKOM'), ('TELECOM', 'DIGI'),
    ('HOUSING', 'RENT'), ('HOUSING', 'CHIRIE'), ('HOUSING', 'ASOCIATIA'), ('HOUSING', 'PROPRIETARI'),
    ('HEALTH', 'CATENA'), ('HEALTH', 'DR MAX'), ('HEALTH', 'HELP NET'), ('HEALTH', 'SENSIBLU'),
    ('HEALTH', 'FARMACIA'), ('HEALTH', 'FARMACIE'), ('HEALTH', 'REGINA MARIA'), ('HEALTH', 'MEDLIFE'),
    ('HEALTH', 'SANADOR'),
    ('ENTERTAINMENT', 'CINEMA CITY'), ('ENTERTAINMENT', 'STEAM'), ('ENTERTAINMENT', 'PLAYSTATION'),
    ('ENTERTAINMENT', 'IABILET'), ('ENTERTAINMENT', 'ENTERTIX'), ('ENTERTAINMENT', 'TICKETMASTER'),
    ('SUBSCRIPTIONS', 'SPOTIFY'), ('SUBSCRIPTIONS', 'NETFLIX'), ('SUBSCRIPTIONS', 'HBO MAX'),
    ('SUBSCRIPTIONS', 'DISNEY PLUS'), ('SUBSCRIPTIONS', 'APPLE'), ('SUBSCRIPTIONS', 'GOOGLE'),
    ('SUBSCRIPTIONS', 'YOUTUBE'), ('SUBSCRIPTIONS', 'MICROSOFT'), ('SUBSCRIPTIONS', 'ADOBE'),
    ('SUBSCRIPTIONS', 'DROPBOX'), ('SUBSCRIPTIONS', 'OPENAI'),
    ('SHOPPING', 'EMAG'), ('SHOPPING', 'ALTEX'), ('SHOPPING', 'AMAZON'), ('SHOPPING', 'IKEA'),
    ('SHOPPING', 'DEDEMAN'), ('SHOPPING', 'DECATHLON'), ('SHOPPING', 'ZARA'), ('SHOPPING', 'PEPCO'),
    ('SHOPPING', 'JYSK'), ('SHOPPING', 'FASHION DAYS'), ('SHOPPING', 'DM'), ('SHOPPING', 'H&M'),
    ('TRAVEL', 'BOOKING'), ('TRAVEL', 'AIRBNB'), ('TRAVEL', 'WIZZ'), ('TRAVEL', 'WIZZAIR'), ('TRAVEL', 'TAROM'),
    ('TRAVEL', 'RYANAIR'), ('TRAVEL', 'HOTEL'),
    ('EDUCATION', 'UDEMY'), ('EDUCATION', 'COURSERA'), ('EDUCATION', 'CARTURESTI'), ('EDUCATION', 'LIBRARIE'),
    ('FEES', 'COMISION'), ('FEES', 'COMISIOANE'), ('FEES', 'TAXA'), ('FEES', 'FEE'),
    ('INCOME', 'SALARIU'), ('INCOME', 'SALARY'), ('INCOME', 'DIVIDEND'), ('INCOME', 'DIVIDENDE'),
    ('TRANSFER', 'ECONOMII'), ('TRANSFER', 'SAVINGS'), ('TRANSFER', 'CONT PROPRIU'),
    ('CASH', 'ATM'), ('CASH', 'RETRAGERE NUMERAR'), ('CASH', 'NUMERAR'), ('CASH', 'CASH')
) AS k(code, pattern)
JOIN category c ON c.code = k.code;
